layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Ruby
    web_url: https://github.com/topics/ruby
    image_url: http://budiirawan.com/wp-content/uploads/2015/04/ruby-logo.png

  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://github.com/voodootikigod/logo.js/blob/master/js.png?raw=true

  - name: AWS
    web_url: https://github.com/topics/aws
    image_url: https://raw.githubusercontent.com/github/explore/fbceb94436312b6dacde68d122a5b9c7d11f9524/topics/aws/aws.png

